### ISSUE TITLE
Some float<->str conversions have incorrect results, sometimes fail

### ISSUE THREAD

**Issue by SaladDais** [SaladDais/Lummao#5]
We use LSL-PyOptimizer's typecast function for runtime casts, but it's failing on a couple of cases from the second LSL language conformance test:

```
>>> lslopt.lslfuncs.typecast(lslopt.lslfuncs.F32(1.4e-45), str)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/user/source/LSL-PyOptimizer/lslopt/lslbasefuncs.py", line 649, in typecast
    return InternalTypecast(val, out, InList, f32)
  File "/home/user/source/LSL-PyOptimizer/lslopt/lslbasefuncs.py", line 470, in InternalTypecast
    if out == unicode: return f2s(val, 6)
  File "/home/user/source/LSL-PyOptimizer/lslopt/lslbasefuncs.py", line 391, in f2s
    while s[i] in u'0.':
IndexError: string index out of range
```

because it gets formatted as `0.00000` internally, but its float val is not equal to `0.0`, making that loop explode.

also:

```
>>> lslopt.lslfuncs.typecast("-0.0", float)
0.0
```

when it should be `-0.0` seems to be due to a missing `math.copysign()` call when replacing things equivalent to 0.0 with 0.0 itself.

LSL-PyOptimizer itself doesn't run into either of these issues when optimizing an LSL script. Need to dig in more, things might be special-cased further up in the folding code.

**Comment by SaladDais** [comment]
Never mind, looks like these do affect PyOptimizer as well:

```lsl
default {
  state_entry() { llOwnerSay((string)1.4e-45); }
}
```

and

```lsl
default {
  state_entry() { llOwnerSay((string)((float)"-0.0")); }
}
```
